name: Publish to GITHUB NPM
on:
  release:
    types: [created]
jobs:
  Publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies 🔧
        run: npm ci
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GP_TOKEN }}
          REGISTRY1: 'npm.pkg.github.com'
          REGISTRY2: '@fiusdevelopment:registry=https://npm.pkg.github.com'